import Cookies from "cookies";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";

export async function getServerSideProps(context) {
    const at = Date.now();
    const cookies = new Cookies(context.req, context.res);
    cookies.set(
        "demo-cookie",
        Date.now(),
        {
            path: "/",
            sameSite: "lax",
            httpOnly: true,
            secure: false,
        }
    );
    return {
        props: {at: at}, // will be passed to the page component as props
    }
};

export default function Home({at}) {
  const [cookiesFromAPI, setCookiesFromApi] = useState("");


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js at {at}!</a>
        </h1>

        <button onClick={() => { fetch('api/hello').then(response => response.json()).then(data => setCookiesFromApi(JSON.stringify(data))) }}>Do a call Hello API</button>
        <label>Response data</label>
        <div>{cookiesFromAPI}</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
